# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-27 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepicture',
            name='user',
            field=models.CharField(max_length=40),
        ),
    ]
