# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-28 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='upvoted_feature',
        ),
        migrations.AddField(
            model_name='upvote',
            name='upvoted_feature',
            field=models.ManyToManyField(default=None, to='features.Features'),
        ),
    ]
