# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-28 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
        ('checkout', '0002_auto_20181129_0902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='upvoted_feature',
        ),
        migrations.AddField(
            model_name='upvote',
            name='upvoted_feature',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='features.Features'),
        ),
    ]
