# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-28 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20181129_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='upvoted_feature',
            field=models.TextField(),
        ),
    ]
