# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-27 03:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181127_1212'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs_features', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('upvotes', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('To Do', 'To do'), ('Doing', 'Doing'), ('Done', 'Done')], default='To Do', max_length=40)),
                ('picture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ProfilePicture')),
                ('username', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
