# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-27 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bugs_features', '0002_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='feature_ticket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bugs_features.Features'),
        ),
    ]
