# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-02 02:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='features',
            name='in_progress_date',
        ),
    ]
