# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-02 02:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_remove_features_in_progress_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='in_progress_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
