# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-02 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_auto_20181202_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='features',
            name='waiting_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
