# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-27 23:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20181128_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='bug_ticket',
            new_name='ticket',
        ),
    ]
