# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-02 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_auto_20181202_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugs',
            name='created_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
