# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 02:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bugs', '0003_auto_20181128_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugUpvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvoted_bug', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bugs.Bugs')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
